//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGarage.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyGarage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Ansicht ähnelt.
        /// </summary>
        public static string _Ansicht {
            get {
                return ResourceManager.GetString("_Ansicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Bearbeiten ähnelt.
        /// </summary>
        public static string _Bearbeiten {
            get {
                return ResourceManager.GetString("_Bearbeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Beenden ähnelt.
        /// </summary>
        public static string _Beenden {
            get {
                return ResourceManager.GetString("_Beenden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Datei ähnelt.
        /// </summary>
        public static string _Datei {
            get {
                return ResourceManager.GetString("_Datei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Einstellungen ähnelt.
        /// </summary>
        public static string _Einstellungen {
            get {
                return ResourceManager.GetString("_Einstellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Hilfe ähnelt.
        /// </summary>
        public static string _Hilfe {
            get {
                return ResourceManager.GetString("_Hilfe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Hilfe anzeigen ähnelt.
        /// </summary>
        public static string _Hilfe_anzeigen {
            get {
                return ResourceManager.GetString("_Hilfe_anzeigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Über MyGarage ähnelt.
        /// </summary>
        public static string _Über_MyGarage {
            get {
                return ResourceManager.GetString("_Über_MyGarage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string Abbrechen {
            get {
                return ResourceManager.GetString("Abbrechen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        /// </summary>
        public static string Beschreibung {
            get {
                return ResourceManager.GetString("Beschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Betriebsstunden ähnelt.
        /// </summary>
        public static string Betriebsstunden {
            get {
                return ResourceManager.GetString("Betriebsstunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum ähnelt.
        /// </summary>
        public static string Datum {
            get {
                return ResourceManager.GetString("Datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details (F10) ähnelt.
        /// </summary>
        public static string Details_F10 {
            get {
                return ResourceManager.GetString("Details_F10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Durchgeführt von ähnelt.
        /// </summary>
        public static string Durchgeführt_von {
            get {
                return ResourceManager.GetString("Durchgeführt_von", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erstzulassung ähnelt.
        /// </summary>
        public static string Erstzulassung {
            get {
                return ResourceManager.GetString("Erstzulassung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fahrzeug hinzufügen ähnelt.
        /// </summary>
        public static string Fahrzeug_hinzufügen {
            get {
                return ResourceManager.GetString("Fahrzeug_hinzufügen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FIN ähnelt.
        /// </summary>
        public static string FIN {
            get {
                return ResourceManager.GetString("FIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hersteller ähnelt.
        /// </summary>
        public static string Hersteller {
            get {
                return ResourceManager.GetString("Hersteller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzufügen ähnelt.
        /// </summary>
        public static string Hinzufügen {
            get {
                return ResourceManager.GetString("Hinzufügen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzufügen (F11) ähnelt.
        /// </summary>
        public static string Hinzufügen_F11 {
            get {
                return ResourceManager.GetString("Hinzufügen_F11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HSN ähnelt.
        /// </summary>
        public static string HSN {
            get {
                return ResourceManager.GetString("HSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HU durchgeführt ähnelt.
        /// </summary>
        public static string HU_durchgeführt {
            get {
                return ResourceManager.GetString("HU_durchgeführt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kennzeichen ähnelt.
        /// </summary>
        public static string Kennzeichen {
            get {
                return ResourceManager.GetString("Kennzeichen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kilometer ähnelt.
        /// </summary>
        public static string Kilometer {
            get {
                return ResourceManager.GetString("Kilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KW ähnelt.
        /// </summary>
        public static string KW {
            get {
                return ResourceManager.GetString("KW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen (Entf) ähnelt.
        /// </summary>
        public static string Löschen_Entf {
            get {
                return ResourceManager.GetString("Löschen_Entf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen (F12) ähnelt.
        /// </summary>
        public static string Löschen_F12 {
            get {
                return ResourceManager.GetString("Löschen_F12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mängel ähnelt.
        /// </summary>
        public static string Mängel {
            get {
                return ResourceManager.GetString("Mängel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modell ähnelt.
        /// </summary>
        public static string Modell {
            get {
                return ResourceManager.GetString("Modell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nächste HU ähnelt.
        /// </summary>
        public static string Nächste_HU {
            get {
                return ResourceManager.GetString("Nächste_HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nächste SP ähnelt.
        /// </summary>
        public static string Nächste_SP {
            get {
                return ResourceManager.GetString("Nächste_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neu (Enter) ähnelt.
        /// </summary>
        public static string Neu_Enter {
            get {
                return ResourceManager.GetString("Neu_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Reparatur ähnelt.
        /// </summary>
        public static string Neue_Reparatur {
            get {
                return ResourceManager.GetString("Neue_Reparatur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PS ähnelt.
        /// </summary>
        public static string PS {
            get {
                return ResourceManager.GetString("PS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reparaturen/Wartungen ähnelt.
        /// </summary>
        public static string Reparaturen_Wartungen {
            get {
                return ResourceManager.GetString("Reparaturen_Wartungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SP durchgeführt ähnelt.
        /// </summary>
        public static string SP_durchgeführt {
            get {
                return ResourceManager.GetString("SP_durchgeführt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchen (F9) ähnelt.
        /// </summary>
        public static string Suchen_F9 {
            get {
                return ResourceManager.GetString("Suchen_F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TSN ähnelt.
        /// </summary>
        public static string TSN {
            get {
                return ResourceManager.GetString("TSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Typ ähnelt.
        /// </summary>
        public static string Typ {
            get {
                return ResourceManager.GetString("Typ", resourceCulture);
            }
        }
    }
}
